//
//  ApiParameterStatics.swift
//  TOD
//
//  Created by My Mac on 27/05/21.
//

import Foundation

struct ApiParameterStatics {
    
    static let abn_number = "abn_number"
    static let address = "address"
    static let createdAt = "createdAt"
    static let displayName = "displayName"
    static let email = "email"
    static let user_dl = "user_dl"
    static let verified = "verified"
    static let isUploaded = "isUploaded"
    static let value = "value"
    static let city = "city"
    static let country = "country"
    static let doorNumber = "doorNumber"
    static let pincode = "pincode"
    static let street = "street"
    static let url = "url"
    static let permit_needed = "permit_needed"
    static let service_code = "service_code"
    static let service_option_code = "service_option_code"
    static let service_type = "service_type"
    static let service_name = "service_name"
    static let permit_description = "permit_description"
    static let permit_example = "permit_example"
    static let permit_name = "permit_name"
    static let permit_file = "permit_file"
    static let permit_verified = "permit_verified"
    static let permit_submitted = "permit_submitted"
    static let services = "services"
    static let description = "description"
    static let title = "title"
    static let phoneNumber = "phoneNumber"
    static let state = "state"
    static let buisness_name = "buisnessname"
    static let plumbing = "Plumbing"
    static let complete_address = "complete_address"
    static let last_location_maps = "last_location_maps"
    static let last_location_updated_on = "last_location_updated_on"
    static let last_pincode = "last_pincode"
    static let last_status_updated = "last_status_updated"
    static let sp_id = "sp_id"
    static let status = "status"
    static let twilio_client_id = "twilio_client_id"
    static let available_pincodes = "available_pincodes"
    static let message = "message"
    static let subject = "subject"
    static let user_email = "user_email"
    static let user_id = "user_id"
    static let user_mobile = "user_mobile"
    static let user_name = "user_name"
    static let Url = "Url"
    static let to = "To"
    static let from = "From"
    static let authorization = "Authorization"
    static let basic = "Basic"
    static let content_type = "Content-Type"
    static let x_www_form_urlencoded = "application/x-www-form-urlencoded"
    static let job_completion_status = "job_completion_status"
    static let job_id = "job_id"
    static let caller_number = "caller_number"
    static let client_id = "client_id"
    static let feedback_rating = "feedback_rating"
    static let job_location_pincode = "job_location_pincode"
    static let job_scheduled_time = "job_scheduled_time"
    static let opportunity_id = "opportunity_id"
    static let requested_service_option_code = "requested_service_option_code"
    static let requested_service_code = "requested_service_code"
    static let requested_service = "requested_service"
    static let inprogress = "inprogress"
    static let completed = "completed"
    static let scheduled = "scheduled"
    static let service = "services"
    static let access_token = "access_token"
    static let expires_on = "expires_on"
    static let twilio_client = "twilio_client"
    static let display_name = "display_name"
    static let phone_number = "phone_number"
    static let door_number = "door_number"
    static let isLocalNotification = "isLocalNotification"
    static let token_ios = "token_ios"
    static let twi_account_sid = "twi_account_sid"
    static let twi_bridge_token = "twi_bridge_token"
    static let twi_from = "twi_from"
    static let twi_to = "twi_to"
    static let twi_message_id = "twi_message_id"
    static let twi_call_sid = "twi_call_sid"
    static let aps = "aps"
    static let twi_message_type = "twi_message_type"
    static let twi_params = "twi_params"
    static let call_ended_time = "call_ended_time"
    static let call_status = "call_status"
    static let rejected = "rejected"
    static let answered = "answered"
    static let no_answer = "no-answer"
    static let call_inprogress = "call-inprogress"
    static let called_tradies = "called_tradies"
    static let call_finished = "call_finished"
    static let job_acceptance_time = "job_acceptance_time"
    static let job_acceptance_status = "job_acceptance_status"
    static let recorded_call_location = "recorded_call_location"
    static let tradie_email = "tradie_email"
    static let tradie_name = "tradie_name"
    static let tradie_phone_number = "tradie_phone_number"
    static let accepted = "accepted"
    static let am_symbol = " AM"
    static let pm_symbol = " PM"
    static let called_at = "called_at"
    static let available_tradies_twilio_client = "available_tradies_twilio_client"
    static let push = "push"
    static let access_token_android = "access_token_android"
    static let access_token_ios = "access_token_ios"
}


